### ISSUE TITLE
about the node feature 

### ISSUE THREAD

**Issue by SharonLee19** [hitlic/DGCNN-tensorflow#1]
hello,
i have met one problem,can you help me?
i want to use the node feature and construction ,eg the Synthie.And when i run the code,it shows :

2020-08-31 11:33:51,451 - loading data
class_num           4
conv1d_channels     [15, 30]
conv1d_kernel_size  [0, 5]
dense_dim           128
feature_dim         16
gcnn_dims           [30, 30, 30, 1]
k                   30
keep_prob           1
learning_rate       0.0001
node_feature_dim    15
node_label_dim      1

2020-08-31 11:33:52,089 - 训练数据量 360，测试数据量 40
F:\Anaconda3\envs\tensor112\lib\site-packages\tensorflow\python\ops\gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-08-31 11:33:52.699053: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "D:/work/code/DGCNN-tensorflow1.12.0-master/DGCNN-tensorflow-master/train.py", line 108, in <module>
    loss, acc, auc = loop_dataset(model, params, train_set, sess, batch_size)
  File "D:/work/code/DGCNN-tensorflow1.12.0-master/DGCNN-tensorflow-master/train.py", line 55, in loop_dataset
    predicts, loss, acc, _ = sess.run(to_run, feed_dict=feed_dict)
  File "F:\Anaconda3\envs\tensor112\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "F:\Anaconda3\envs\tensor112\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4750, 15) for Tensor 'place_hoders/batch_node_features:0', which has shape '(?, 16)'

Process finished with exit code 1

i add the params.set("feature_dim", 15) in step0 ,but it stlii no use.
thx

**Comment by hitlic** [comment]
I'm not sure what the problem is based on your information. I don't have a tf1 environment now, but I had implemented a tf2 version of DGCNN, which I hope will be useful to you.
https://github.com/hitlic/SEAL-tf2/blob/master/dgcnn_models.py
